/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckRouteImport } from './routes/check'
import { Route as DecodeRouteImport } from './routes/decode'
import { Route as HowRatingsWorkRouteImport } from './routes/how-ratings-work'
import { Route as RateRouteImport } from './routes/rate'
import { Route as ClaimsIndexRouteImport } from './routes/claims.index'
import { Route as ClaimsSlugRouteImport } from './routes/claims.$slug'
import { Route as StoryIdRouteImport } from './routes/story.$id'
import { Route as ApiPublicHooksFeedsRouteImport } from './routes/api/public/hooks/feeds'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const DecodeRoute = DecodeRouteImport.update({
  id: '/decode',
  path: '/decode',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRatingsWorkRoute = HowRatingsWorkRouteImport.update({
  id: '/how-ratings-work',
  path: '/how-ratings-work',
  getParentRoute: () => rootRouteImport,
} as any)
const RateRoute = RateRouteImport.update({
  id: '/rate',
  path: '/rate',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsIndexRoute = ClaimsIndexRouteImport.update({
  id: '/claims/',
  path: '/claims/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsSlugRoute = ClaimsSlugRouteImport.update({
  id: '/claims/$slug',
  path: '/claims/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdRoute = StoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksFeedsRoute = ApiPublicHooksFeedsRouteImport.update({
  id: '/api/public/hooks/feeds',
  path: '/api/public/hooks/feeds',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/decode': typeof DecodeRoute
  '/how-ratings-work': typeof HowRatingsWorkRoute
  '/rate': typeof RateRoute
  '/claims/$slug': typeof ClaimsSlugRoute
  '/story/$id': typeof StoryIdRoute
  '/claims/': typeof ClaimsIndexRoute
  '/api/public/hooks/feeds': typeof ApiPublicHooksFeedsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/decode': typeof DecodeRoute
  '/how-ratings-work': typeof HowRatingsWorkRoute
  '/rate': typeof RateRoute
  '/claims/$slug': typeof ClaimsSlugRoute
  '/story/$id': typeof StoryIdRoute
  '/claims': typeof ClaimsIndexRoute
  '/api/public/hooks/feeds': typeof ApiPublicHooksFeedsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/decode': typeof DecodeRoute
  '/how-ratings-work': typeof HowRatingsWorkRoute
  '/rate': typeof RateRoute
  '/claims/$slug': typeof ClaimsSlugRoute
  '/story/$id': typeof StoryIdRoute
  '/claims/': typeof ClaimsIndexRoute
  '/api/public/hooks/feeds': typeof ApiPublicHooksFeedsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check'
    | '/decode'
    | '/how-ratings-work'
    | '/rate'
    | '/claims/$slug'
    | '/story/$id'
    | '/claims/'
    | '/api/public/hooks/feeds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check'
    | '/decode'
    | '/how-ratings-work'
    | '/rate'
    | '/claims/$slug'
    | '/story/$id'
    | '/claims'
    | '/api/public/hooks/feeds'
  id:
    | '__root__'
    | '/'
    | '/check'
    | '/decode'
    | '/how-ratings-work'
    | '/rate'
    | '/claims/$slug'
    | '/story/$id'
    | '/claims/'
    | '/api/public/hooks/feeds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckRoute: typeof CheckRoute
  DecodeRoute: typeof DecodeRoute
  HowRatingsWorkRoute: typeof HowRatingsWorkRoute
  RateRoute: typeof RateRoute
  ClaimsSlugRoute: typeof ClaimsSlugRoute
  StoryIdRoute: typeof StoryIdRoute
  ClaimsIndexRoute: typeof ClaimsIndexRoute
  ApiPublicHooksFeedsRoute: typeof ApiPublicHooksFeedsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decode': {
      id: '/decode'
      path: '/decode'
      fullPath: '/decode'
      preLoaderRoute: typeof DecodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-ratings-work': {
      id: '/how-ratings-work'
      path: '/how-ratings-work'
      fullPath: '/how-ratings-work'
      preLoaderRoute: typeof HowRatingsWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate': {
      id: '/rate'
      path: '/rate'
      fullPath: '/rate'
      preLoaderRoute: typeof RateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/': {
      id: '/claims/'
      path: '/claims'
      fullPath: '/claims/'
      preLoaderRoute: typeof ClaimsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/$slug': {
      id: '/claims/$slug'
      path: '/claims/$slug'
      fullPath: '/claims/$slug'
      preLoaderRoute: typeof ClaimsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id': {
      id: '/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof StoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/feeds': {
      id: '/api/public/hooks/feeds'
      path: '/api/public/hooks/feeds'
      fullPath: '/api/public/hooks/feeds'
      preLoaderRoute: typeof ApiPublicHooksFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckRoute: CheckRoute,
  DecodeRoute: DecodeRoute,
  HowRatingsWorkRoute: HowRatingsWorkRoute,
  RateRoute: RateRoute,
  ClaimsSlugRoute: ClaimsSlugRoute,
  StoryIdRoute: StoryIdRoute,
  ClaimsIndexRoute: ClaimsIndexRoute,
  ApiPublicHooksFeedsRoute: ApiPublicHooksFeedsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
